name: Docker Container Builds

on:
  push:
    branches:
      - master
      - main
      - dev
      - develop


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dbType: ephemeral
          - dbType: postgres
          - dbType: mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo "DOCKER_TAG=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Should docker tag be latest?
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Manually configured docker tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "DOCKER_TAG={{ github.event.inputs.dockerTagName }}" >> $GITHUB_ENV

      - name: Show us the DOCKER_TAG
        run: echo "${{ env.DOCKER_TAG}}"

      - name: Build and push Tbyte Docker images
        uses: docker/build-push-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push pwpush-${{ matrix.dbType }} Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          file: ./containers/docker/pwpush-${{ matrix.dbType }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: tetrabyteit/securesend:${{ env.DOCKER_TAG }}
