name: Docker Container Builds

on:
  push:
    branches:
      - master
      - dev
      - dev-tbyte
    tags:
      - "stable"
      - "v*.*.*"

env:
  DOCKER_PUSH: true

jobs:
  pwpush-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tetrabyteit/securesend
          flavor: |
            latest=false
          tags: |
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest
            type=ref,event=branch

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=tetrabyteit/securesend:buildcache
          cache-to: type=registry,ref=tetrabyteit/securesend:buildcache,mode=max

  worker-container-master:
    needs: pwpush-container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tetrabyteit/pwpush-worker
          flavor: |
            latest=false
          tags: |
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest
            type=ref,event=branch

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile.worker
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=tetrabyteit/pwpush-worker:buildcache
          cache-to: type=registry,ref=tetrabyteit/pwpush-worker:buildcache,mode=max,ignore-error=${{ env.DOCKER_PUSH == 'false' }}

  worker-container-dev:
    needs: pwpush-container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev-tbyte'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tetrabyteit/pwpush-worker
          flavor: |
            latest=false
          tags: |
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest
            type=ref,event=branch

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile.worker
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=tetrabyteit/pwpush-worker:buildcache
          cache-to: type=registry,ref=tetrabyteit/pwpush-worker:buildcache,mode=max,ignore-error=${{ env.DOCKER_PUSH == 'false' }}
